### ISSUE TITLE
Circular dependency neon_mq_connector

### ISSUE THREAD

**Issue by NeonBohdan** [NeonGeckoCom/neon_api_proxy#60]
[neon-utils](https://github.com/NeonGeckoCom/neon-skill-utils/blob/dev/requirements/requirements.txt) has requirements
```
neon_mq_connector~=0.2
neon_api_proxy~=0.2,>=0.2.1a4
```

but [neon-api-proxy](https://github.com/NeonGeckoCom/neon_api_proxy/blob/master/requirements/requirements.txt) has requirements
```
neon_utils~=0.13
neon_mq_connector~=0.3.0
```

This causes deps conflict in `neon_mq_connector`, if it wasn't installed previosly 
Need to update to something like `neon_mq_connector~=0.3`, if possible

**Comment by NeonDaniel** [comment]
Resolved by https://github.com/NeonGeckoCom/neon_mq_connector/pull/80
